version: '2'
services:
  web:
    container_name: ffm_node_prod
    extends:
      file: docker-compose.common.yml
      service: web
    build: 
      context: .
      dockerfile: Dockerfile-prod
    command: npm run start:prod
    environment:
     - NODE_ENV=production
    depends_on:
     - db
    ports:
     - "8443:8443"
    volumes:
     - ./:/opt/ffmedia
     - node_modules:/opt/ffmedia/node_modules
     - public:/opt/ffmedia/public
     - uploads:/opt/ffmedia/uploads
    networks:
      - default
  db:
    container_name: ffm_mongo_prod
    extends:
      file: docker-compose.common.yml
      service: db
    image: mongo:3.2
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - db_volume:/data/db
    networks:
      - default
volumes:
  db_volume:
  node_modules:
  public:
  uploads:
networks:
  default:

